SELECT DISTINCT ISP.ISP_ID
  , ISP.STUDENT_KEY
  , ISP.TYPE_OF_SERVICE
  , ISP.SCHOOL_YEAR
  , ISP.INSTRUCTIONAL_PROGRAM_NUM AS IPN
  , ISP.ENROLLMENT_REASON
  , ISP.WITHDRAWAL_REASON
  , ISP.ENGLISH_LANGUAGE_BACKGROUND AS ELB
  , ISP.SCHOOL_BU_ID
  , ISP.BEGIN_DATE
  , ISP.END_DATE
  , SCA.LOCAL_CLASS_NUMBER
  , SCA.SCA_BEGIN_DATE
  , SCA.SCA_END_DATE
  , CS.COURSE_CODE
  , CS.CLASS_TYPE
  , CS.CS_BEGIN_DATE
  , CS.CS_END_DATE
  , CS.TEST_WINDOW
  , CN.COURSE_NAME
  , CN.STATUS AS COURSE_STATUS
  , CN.BEGIN_SCHOOL_YEAR
  , CN.END_SCHOOL_YEAR
  , CN.COURSE_TYPE
  , SCH.DISTRICT_NO
  , DIS.DISTRICT_NAME
  , SCH.SCHOOL_NO
  , SCH.SCHOOL_NAME
FROM (SELECT * FROM INSTRUCTIONAL_SERVICE_PERIOD WHERE SCHOOL_YEAR = 2020) ISP
  JOIN (SELECT * FROM STUDENT_CLASS_ASSIGNMENT WHERE SCHOOL_YEAR = 2020) SCA
    ON ISP.ISP_ID = SCA.ISP_ID
    -- AND ISP.SCHOOL_YEAR = SCA.SCHOOL_YEAR
    AND ISP.INSTRUCTIONAL_PROGRAM_NUM = SCA.INSTRUCTIONAL_PROGRAM_NUM
    AND ISP.SCHOOL_BU_ID = SCA.SCHOOL_BU_ID
  JOIN (SELECT * FROM CLASS_SECTION WHERE SCHOOL_YEAR = 2020) CS
    ON ISP.INSTRUCTIONAL_PROGRAM_NUM = CS.INSTRUCTIONAL_PROGRAM_NUM
    -- AND ISP.SCHOOL_YEAR = CS.SCHOOL_YEAR
    AND SCA.LOCAL_CLASS_NUMBER = CS.LOCAL_CLASS_NUMBER
    AND ISP.SCHOOL_BU_ID = CS.SCHOOL_BU_ID
  JOIN COURSE_NEW CN ON CS.COURSE_CODE = CN.COURSE_CODE
  JOIN SCHOOL SCH ON ISP.SCHOOL_BU_ID = SCH.SCHOOL_BU_ID
  JOIN DISTRICT DIS ON SCH.DISTRICT_NO = DIS.DISTRICT_NO
